# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Cache@2
  inputs:
    key: '"funcs" | maven |"$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
    path: $(MAVEN_CACHE_FOLDER)
  displayName: Cache Maven local repo
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'puppyplacepetshop'
    scannerMode: 'Other'
- task: Maven@3
  displayName: 'Unit tests'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
    goals: 'clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=puppyplacepetshop_PuppyPlace'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: JaCoCo
    codeCoverageFailIfEmpty: false
    codeCoverageRestoreOriginalPomXml: true
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'
#- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: Bash@3
  displayName: 'Building application'
  inputs:
    targetType: 'inline'
    script: 'mvn package -Dmaven.test.skip=true'
- task: CopyFiles@2
  displayName: 'Copying files'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
