# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'puppyplacepetshop'
    scannerMode: 'Other'
- task: Maven@3
  displayName: 'Unit tests'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m '
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    isJacocoCoverageReportXML: true
    sonarQubeRunAnalysis: true
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenAuthenticateFeed: false
    goals: 'clean verify -Dsonar.projectKey=puppyplacepetshop_PuppyPlace -Dsonar.qualitygate.wait=true -Dmaven.repo.local=$(Pipeline.Workspace)/.m2/repository sonar:sonar'
- task: SonarCloudPublish@1
- task: Bash@3
  displayName: 'Building application'
  inputs:
    targetType: 'inline'
    script: 'mvn package -Dmaven.test.skip=true'
- task: Docker@2
  inputs:
    containerRegistry: 'puppyplace-9985'
    repository: 'puppyplace-api'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
- task: CopyFiles@2
  displayName: 'Copying files'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
