-- public."lead" definition

-- Drop table

-- DROP TABLE public."lead";

CREATE TABLE public."lead" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cellphone varchar(255) NULL,
	email varchar(255) NULL,
	interest varchar(255) NULL,
	name varchar(255) NULL,
	CONSTRAINT lead_pkey PRIMARY KEY (id)
);